name: wind
age: 20
#list:
#  'one'
#  'two'
#  'three'

fruits: 1,2,3,4,5,6,7,8,9

valueList:
  -13579
  -246810

valueMapList:
  - name: bob
    age: 21
  - name: caven
    age: 31
language:
  name: java
  level: 6

spring:
  datasource:
          name: ec
          url: jdbc:mysql://127.0.0.1/ec?characterEncoding=utf-8&useSSL=false
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource

#  spring.devtools.restart.enabled=true

  mybatis:
    mapper-locations: classpath:mapper/*.xml
#    mybatis: configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

  server:
     port: 8677
